name: Test
on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          force-avd-creation: false
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          script: ./gradlew executeScreenshotTests