name: Test
on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          target: google_apis
          arch: x86_64
          profile: Pixel 5
          script: ./gradlew executeScreenshotTests